# Generated by Django 3.2.15 on 2022-12-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='ctr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='username',
            field=models.CharField(default='xxx', max_length=2083),
        ),
    ]
