name: Linting Check
on:
  push:
    branches: [ "arvind/badges" ]
  pull_request:
    branches:
      - "arvind/badges"
  workflow_dispatch:
  schedule:
    - cron: '18 18 * * 2'
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered on branch ${{ github.ref }}."

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install -r url_shortner_server/requirements.txt
      - name: Lint with flake8
        run: flake8
